### ISSUE TITLE
Cors headers are not set when an error is returned from the handler

### ISSUE THREAD

**Issue by mdaffin** [dbrgn/iron-cors-rs#4]
If the wrapped handler returns an error the cors headers are not set at all, leading to the ui being unable to obtain the reason for the failure if one was set in the body. This makes it impossible to use after middleware to handle error messages gracefully without having to worry about the cors headers.

I would expect the headers to be set on every request in spite of any errors encountered. This way the headers are set and ready for remaining middleware to respond to the client correctly.

**Comment by dbrgn** [comment]
You are right, that is not intended. I'll try to fix it once I find time to do so. PRs are welcome of course!

**Comment by mdaffin** [comment]
In the `CorsHandlerAllowAny` impl replacing 

```
        let mut res = try!(self.handler.handle(req));

        // Add Access-Control-Allow-Origin header to response
        res.headers.set(headers::AccessControlAllowOrigin::Value("*".into()));

        Ok(res)
```
with 
```
        match self.handler.handle(req) {
            Ok(mut res) => {
                res.headers.set(headers::AccessControlAllowOrigin::Any);
                Ok(res)
            }
            Err(mut err) => {
                err.response.headers.set(headers::AccessControlAllowOrigin::Any);
                Err(err)
            }
        }
```
at least compiles and runs the existing tests successfully but I don't have time to fully test it at the moment.

**Comment by dbrgn** [comment]
@mdaffin see #5. would you like to test that branch?

**Comment by mdaffin** [comment]
Thanks. Will have a look at it when I get a moment.

**Comment by mdaffin** [comment]
@dbrgn I have tested #5 with my application and looks like it has fixed the problem.

**Comment by dbrgn** [comment]
Version 0.5.1 containing the fix is now on crates.io!
